name: Build & Deploy
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  push:
    branches:
      - main
jobs:
  Build:
    name: Build & Push Docker images of the Apps
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - name: Check out
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0
      - name: Login to GitHub container registry
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a # v2.1.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build image
        env:
          IMAGE_TAG: ${{ github.sha }}
        run: |
          echo "-- INFO: Building image...."
          docker build -t ghcr.io/mashail/hello:${IMAGE_TAG} ./apps/hello/
          echo "-- INFO: Image built successfully 🎉."

          echo "-- INFO: Pushing image..."
          docker push ghcr.io/mashail/hello:${IMAGE_TAG}
          echo "-- INFO: Image pushed successfully 🎉."

  Deploy:
    runs-on: ubuntu-latest
    name: Deploy Apps
    de
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - name: Check out
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0
      - run: pwd